<!DOCTYPE html>
<html lang="pt-br">
<head>
<?php include "data.inc";?>
<meta charset="utf-8"/>
<link rel="stylesheet" type="text/css" href="estilo.css">
<title>Rei da Pesca</title>
</head>
<body>
<?php include "header.inc";?>
<?php include "menu.inc";?>
<br/><br/>
<hr>
<h1>Carretilhas</h1>
<p>A carretilha é considerada melhor que o molinete nos trabalhos com vara e isca, mas seu manejo exige um pouco mais de experiência. Depois da prática, as vantagens da carretilha são arremessos mais longos e precisos, maior controle das iscas e maior força de tração no momento da briga com o peixe. Por outro lado, as carretilhas formam cabeleiras (para os iniciantes), são mais difíceis para arremessos com iscas leves e pior ainda quando forem contra o vento.</p>
<p><img src="imagens/perfilbaixo.jpg" align=left hspace="10"><h3>Lançamento (perfil baixo):</h3>São equipamentos fisicamente pequenos, utilizados para pesca de arremesso. São mais completos em recursos para o pescador, oferecem muito controle e precisão nos arremessos, possuem maior capacidade de tração, não torcem a linha, são mais leves, estéticos e práticos.</p><br/>
<p><img src="imagens/perfilalto.jpg" align=left hspace="10"><h3>Trolling (perfil alto):</h3>São carretilhas de grande porte com super capacidade de armazenamento de linha, são pesadas e dispõem de muito pouco recurso ( porém precisos ), não servem para arremesso e possuem uma capacidade de tração extremamente alta.</p><br/>
<p><img src="imagens/fly.jpg" align=left hspace="10"><h3>Fly:</h3>São instrumentos utilizados somente nesta modalidade, servindo somente como depósito de linha, auxiliando muito pouco no exercício da pesca, os recursos são precários.</p><br/>
<h3 align="center"> COMPONENTES DA CARRETILHA</h3>
<p><img src="imagens/freio.jpg" align=left hspace="10"><h3>Freios mecânicos ou magnéticos:</h3>As carretilhas são dotadas de freios mecânicos ou magnéticos, que tem por finalidade evitar a formação de cabeleira.<br/>Para uma boa regulagem do freio, deve-se segurar a vara na horizontal, liberar gradativamente o freio, com a carretilha destravada, até que a isca artificial ou o conjunto, chumbo e isca natural, desça lentamente. Este é o ponto ideal de arremesso.</p>
<p><img src="imagens/gear2.jpg" align=left hspace="10"><h3>Gear Ratio:</h3>A expressão em inglês “Gear ratio ” indica a relação de recolhimento.<br/>Exemplo: Se sua carretilha vier com a nomenclatura Gear 6.3:1 – indica que para cada volta que você da na manivela são dadas 6,3 voltas no carretel.<br/>Essa relação é muito importante quando se pesca com iscas artificias, especialmente as de arrasto como hélices e jigs.</p>
<p><img src="imagens/rolamento2.jpg" align=left hspace="10"><h3>Rolamentos:</h3>A expressão em inglês “Ball bearing ” indica ser uma carretilha com rolamentos. Dependendo do modelo, eles podem também ser blindados ou marinizados. Hoje em dia as empresas trabalham para aperfeiçoar e garantir a vida útil dos rolamentos em qualquer situação de pesca se ja em água salgada ou doce. Quanto mais rolamentos, melhor a carretilha.</p><br/>
<h3 align="center">DICAS IMPORTANTES PARA UM MELHOR DESEMPENHO</h3>
<p><h3>Colocando a linha:</h3>A colocação da linha em uma carretilha deve ser feita com o carretel colocado frontalmente, de forma que gire enquanto estiver abastecendo a carretilha. Desta maneira evitam-se torções na linha. Tome cuidado para não enchê-lo demais ou de menos, respeitando um espaço de 1,5m até a borda do carretel. Coloque linha, de preferência, conforme as especificações da linha utilizada. Nunca utilize uma linha fora da especificação da sua carretilha.</p>
<p><h3>Relugando o freio:</h3>Para se arremessar com carretilhas, com o equipamento já montado, execute a regulagem de freio. Isto é feito usando o botão de sintonia fina, de maneira que ao balançar a vara, a linha com a isca ou o peso desça suavemente.<br/>Repita esse procedimento toda vez que for trocar de isca, o peso de uma determinada isca para a outra, interfere na regulagem e pode causar a formação de cabeleiras ou diminuir o desempenho de distância do arremesso.</p>
<p><h3>Regulando a fricção:</h3>Tanto para molinetes, carretilhas ou spincasts, o sistema de fricção normalmente é o mesmo. Um dispositivo de regulagem do carretel permite liberar as linhas com a pressão desejada. Sua necessidade se deve a evitar excessos tanto de resistência como quanto a de liberdade para os peixes.<br/>Com a linha mais solta, os peixes têm facilidade de levar muita linha e enroscá-la ou tomar muita linha de seu carretel. Ainda se estiver muito fechada, pode romper logo nas primeiras corridas. Essa pressão precisa variar de acordo com a linha e modalidade de pescaria que você estiver fazendo.<br/>Um aspecto bastante importante é que a regulagem da fricção deve ser feita a ¼ de resistência da linha usada ou da vara (quando esta for de resistência menor que a linha). Exemplo: se você abasteceu a sua carretilha com linha de 12 libras de resistência, o seu ajuste deverá ser de 3 libras.<br/>Para executar esse ajuste, monte seu conjunto vara, carretilha e a linha passada, coloque uma balança na ponta da linha e aplique pressão na vara. Ela deverá acusar as 3 libras quando começar a soltar linha e, caso a marcação seja inferior, girar a estrela junto à manivela até atingir as 3 libras. Caso marque a maior, girar a estrela no sentido oposto de forma a soltar mais fricção para atingir as 3 libras desejadas. Para conversão de libras em quilos multiplique o valor em libras por 0,4536.<br/>A regulagem da fricção, além de proporcionar maior emoção na hora da pescaria (por proporcionar uma briga mais justa com o peixe), ainda garante uma maior vida útil do equipamento, pois as engrenagens não estarão sendo danificadas.</p>
<p><h3>Arremessando com sua carretilha:</h3>Para executar o arremesso você deve liberar o carretel acionando o botão do lado direito, ou o auto cast, quando a carretilha for dotada deste recurso. Use o polegar para manter o carretel preso. Ao arremessar, alivie a pressão do polegar permitindo que o carretel gire e libere a linha, continuando o movimento.<br/>Importante: no momento que a isca toca na água ou chegar ao alvo desejado, exerça pressão novamente com o polegar, não permitindo que o carretel continue girando, evitando, desta forma, as famosas “cabeleiras”.</p>
<div align="center"><img src="imagens/carretilhas.jpg"></div>
<p><h3>Cuidados de manutenção:</h3>Alguns cuidados de manutenção são importantes para o bom funcionamento de sua carretilha. Após usá-la, trave a fricção e lave-a em água corrente, usando uma escova macia, com atenção para o guia fio e manivela, locais onde pode acumular sujeira como barro ou areia. Após secá-la, lubrifique-a com uma gota de óleo fino específico para carretilhas ou do tipo “Singer”, observando que em alguns pontos você deverá usar um pouco de graxa de “consistência fina”. Repita essa ação após cada pescaria para prolongar a vida útil da sua carretilha.<br/>Nunca utilize graxa espessa ou grafite, esse tipo de produto endurece e trava o equipamento. Se for necessário uma manutenção mais detalhada, use a vista explodida da sua carretilha para identificar os pontos de abertura, caso não sinta segurança em fazer, procure um profissional de manutenção.</p>
<hr>   
<?php include "footer.inc";?>

</body>
</html>