<!DOCTYPE html>
<html lang="pt-br">
<head>
<?php include "data.inc";?>
<meta charset="utf-8"/>
<link rel="stylesheet" type="text/css" href="estilo.css">
<title>Rei da Pesca</title>
</head>
<body>
<?php include "header.inc";?>
<?php include "menu.inc";?>
<br/><br/>
<hr>
<h1>Dicas</h1>
<p><a href="nos.php"><h3>CLIQUE AQUI PARA O GUIA DE NÓS DE PESCA</h3></a></p>
<h3 align="center">COMO OBTER SUCESSO EM SUA PESCARIA</h3>
<p>Todo pescador tem como objetivo conseguir realizar uma pescaria perfeita, em um local agradável, com ótimos peixes, boas brigas, parceiros de pesca agradáveis e clima favorável.<br/>Para isso acontecer, o próprio pescador deve tomar as devidas precauções para não se arrepender de nada e não cometer erros desastrosos.<br/>Como todos nós sabemos, em muitos locais no Brasil já está cada vez mais difícil encontrar e pegar peixes. Cada vez mais os pescadores estão se atualizando, por isso é preciso buscar sempre a qualidade.</p>
<h3>SINAIS IMPORTANTES PARA SABER ONDE MELHOR PESCAR</h3>
<p></p><b>1 - Aves Aquáticas</b><br/>É este o melhor sinal de todos, pois as aves se alimentam de pequenos peixes e, conseqüentemente onde se encontra um o outro está ao lado.<br/>Em um local onde existem diversas aves, com certeza haverá alimentação em abundância de peixinhos. Como sabemos, peixes predadores se alimentam também desses pequenos peixes.<br/>Se tiver que escolher um bom local para pescar, dê preferência para onde haja bandos de aves aquáticas juntas.</p>
<p><b>2 - Ilhas ou Pedras</b><br/>Nesses locais, o melhor sinal será procurar as rochas que mais tenham organismos vivos, tais como mariscos, ostras, cracas, etc.<br/>No caso de uma ilha, tais rochas sempre se encontram do lado de fora, ou seja, onde o mar é aberto. 
Esse sinal também pode ser utilizado nos rios ou baías de litoral.<br/>Em água doce, as pedras são refúgios de pequenos peixes, e é aqui que o peixe maior lhes dará caça.</p>
<p><b>3 - Troncos e/ou Árvores submersas</b><br/>Outro importante sinal que deve ser observado, tanto em rios do litoral como em rios de água doce ou represas.<br/>Muitas são as espécies de peixes predadores que procuram esses locais para se alimentar, pois em volta de paus e árvores parcial ou totalmente submersas, se avolumam organismos vivos, que são as iscas de peixes maiores, como por exemplo o robalo, o black-bass, os tucunarés, etc.</p>
<p><b>5 - Árvores Frutíferas</b><br/>Mais um importante sinal da natureza, e estas tanto podem ser selvagens como caseiras. Várias espécies de peixes se alimentam de frutos. Por exemplo: um pé de goiaba à beira de uma represa.<br/>Se for tempo de goiabas maduras, com certeza as tilápias estarão se alimentando dessa fruta. Então qual a melhor isca que devemos usar nessa época e nesse local ? A goiaba é apenas um exemplo, pois é enorme a variedade de frutos à beira d'água, assim como o peixe citado é apenas outro exemplo.<br/>Se quisermos, poderemos citar, além da tilápia, peixes como o pacu, a carpa, a piracanjuba, a piaba e etc, pois todos têm o mesmo hábito.</p>
<p><b>6 - Pequenos Cursos D'água</b><br/>Consistem outro importante sinal da natureza que tanto pode ser usado em água doce como no mar. Aqui o detalhe é que os peixes grandes ficam à espera do alimento que invariavelmente sairá do pequeno curso d'água. O melhor local para a pesca é na junção das águas.</p>
<p><b>7 - Identificação dos Canais</b><br/>Com certeza os peixes sempre trafegam pela parte mais profunda, ou seja, os canais. A identificação desses locais é ampla e diversa. No mar podemos descobri-los pela formação das ondas. Em baías e rios de litoral, pela formação das pedras ou terra firme. Um exemplo que pode ser citado, na entrada de um canal, se tivermos de um lado praia e do outro lado um morro com pedras, com certeza o leito passará perto do morro. Em rios, será necessário descobrir os remansos, e isso pode ser feito através da observação de plantas aquáticas que ficam na superfície das águas. Em represas, descreveremos bem a moda "caipira". Com um bambu ou uma corda com um peso, vá batendo o fundo da represa. Quando chegar ao canal, a profundidade aumentará repentinamente.</p>
<p><b>8 - Barrancos de Terra Firme</b><br/>É outro bom sinal da natureza, pois além de fundo, é o local onde o predador dá caça aos outros peixes, que não tem oportunidade de fugir. 
Nesse local, prefira pescar sempre observando a categoria do peixe desejado.</p>
<p><b>9 - Cachoeiras ou Corredeiras</b><br/>Quem é que não sabe que nas piracemas, os peixes menores tem que vencer esses obstáculos, rio acima, para a desova?<br/>Pois é, nas corredeiras, os peixes maiores costumam se alimentar, e isso, por si só, já constituiria um excelente local de pesca. Mas não se esqueçam... existe um limite onde pode se pescar, normalmente 200 metros abaixo ou acima desses locais. Não cometa o erro de pescar em local proibido, informe-se bem antes de empreitar uma dessas.</p>
<h3>DICAS IMPORTANTES PARA SE CONQUISTAR UMA BOA PESCARIA</h3>
<p><b>A Prática</b><br/>Só mesmo a prática leva a perfeição, então o melhor a fazer é mesmo praticar bastante, porém não é só isso, é preciso ficar atento aos erros. Sempre que errarmos alguma coisa na pescaria – seja um enrosco, um peixe que escapou, a linha que estourou – ficar atento no que levou a acontecer isso – a linha não resistiu, o arremesso foi mal feito, a fisgada não surtiu efeito – e de imediato procurar a solução, seja perguntando para pescadores mais experientes ou lendo em revistas e jornais especializados, e principalmente não repetir o erro.</p>
<p><b>A Atenção</b><br/>Esse fator elimina mais de 50% dos erros cometidos em pescarias. Procure sempre verificar se os nós estão firmes, o anzol está bem afiado, a forma de prender a isca está correta, entre outros. Observar o comportamento dos peixes, aonde eles devem estar escondidos, quais suas iscas preferidas e seus hábitos principais. Ficar por dentro do que vem acontecendo nos últimos dias no local em que irá pescar: outras pessoas estão tendo sucesso? a água está escura? que iscas estão usando? enfim, tudo isso devemos saber, caso contrário poderemos estar perdendo tempo naquele local.</p>
<p><b>A Comunicação</b><br/>A comunicação é um processo normalmente de três vias. Ela envolve os parceiros que estão pescando conosco, as pessoas residentes no local (piloteiros, donos de hotéis, pesqueiros, ribeirinhos, etc) e os demais pescadores presentes. Agilizar a comunicação significa buscar a informação onde ela estiver disponível e não esperar que venha até nós. Essa agilidade e qualidade de informação certamente irá nos ajudar a ter sucesso. Não tenha medo de perguntar.</p>
<p><b>A Hora Certa e o Silêncio</b><br/>A melhor hora para encontrar as espécies de peixes são no início da manhã e no final da tarde. Isso não quer dizer que não se possa pescar em outros horários. Já ouvimos muitos pescadores dizendo que fisgaram grandes espécies à noite, de madrugada ou ao meio dia, e realmente isso acontece.Já outro fator importantíssimo na pesca de algumas espécies como a Tilápia, o Lambari, Pacu, Piau, entre outros, é o silêncio na pescaria.</p>
<p><b>Papel de Cidadão</b><br/>Para finalizar estas pequenas dicas para obter sucesso na pescaria, salientamos a importância de preservar os peixes e o nosso meio-ambiente. Todos nós queremos pescar em um local bonito, agradável e com peixes, e também sabemos que só depende de nós. Experimente entrar para o time do pesque e solte, ou pelo menos não leve peixe abaixo do tamanho ideal e apenas o que a legislação permite. E nem deixe lixos espalhados no local. Caso você esteja se dirigindo para "aquela pescaria" em um pesque-pague, pesqueiro, etc., lembre-se de que você tem a obrigação de manter o ambiente da maneira como o encontrou. Evite jogar papéis, copos, bitucas de cigarro, etc., dentro do lago, aliás em lugar algum. A grande maioria dos pesqueiros possui latões de lixo bem distribuídos ao redor dos lagos e, caso estejam longe do seu "point" de pesca basta levar sempre uma sacolinha de mercado para guardar as indesejáveis sobras, evitando assim, a poluição visual e ambiental. Lembre-se também de "respeitar" as regras do local evitando arremessos longos e desnecessários para a captura do seu exemplar. Essa última regra ajuda a manter a amizade e a criar novas, possibilitando assim a ampliação da nossa "rede de amigos". Caso mesmo seguindo estas dicas, o pescador não obtenha sucesso, fique tranqüilo, você fez tudo como devia, e lembre-se que a pesca é um esporte, às vezes a gente perde e às vezes a gente ganha.</p>
<hr>
<?php include "footer.inc";?>

</body>
</html>