<!DOCTYPE html>
<html lang="pt-br">
<head>
<?php include "data.inc";?>
<meta charset="utf-8"/>
<link rel="stylesheet" type="text/css" href="estilo.css">
<title>Rei da Pesca</title>
</head>
<body>
<?php include "header.inc";?>
<?php include "menu.inc";?>
<br/><br/>
<hr>
<h1>Linhas</h1>
<p>A linha de pesca, como tudo na vida, sofreu um processo de evolução em suas características, onde com pesquisas nesses 50 anos, apareceram materiais sintéticos de alta resistência e elasticidades. Assim vieram as fibras monofiladas (o nylon, a poliamida e o poliéster) e, em seguida, as de fibras sintéticas microfilamentadas (Kevlar, Spectra), que são microfilamentos trançados.</p>
<p>Poucos pescadores conhecem da capacidade de resistência da sua linha de pesca e de detalhes importantes para sua conservação e durabilidade. Existe o efeito “memória” da linha, que é o tempo em que a linha permanece no carretel do seu molinete e provoca a espiralada e contorções problemáticas na hora do lançamento, provocando embaraços e perda da capacidade de se atingir a distância e alvo desejados.</p>
<p><img src="imagens/convencional.jpg" align=left hspace="10"><h3>Linha Convencional</h3>Em se tratando no uso das linhas convencionais para as diversas modalidades da pesca esportiva, temos no mercado uma infinidade de boas marcas. Propriamente falando na pesca de arremesso, a busca de se alcançar longas distâncias (canais), para lançamentos produtivos, além arrebentação, ensejou uma revolução benéfica para os desportistas que labutam nos torneios ou competições organizadas pelos clubes de pesca.<br/><br/>Além das nossas linhas convencionais, encontradas nas casas especializadas, houve o advento das importações de material de pesca (molinetes, varas, anzóis, linhas etc.) e que trouxe um campo excelente para o aprimoramento e busca de tecnologia mais atualizada, fazendo com que todo o segmento de material de pesca colocado à disposição dos pescadores fosse modernizado e acessível.</p><br/>
<p><img src="imagens/super.jpg" align=left hspace="10"><h3>As Super-Linhas</h3>Ultimamente temos ouvido uma insistente pergunta:”E as super-linhas vão desbancar as linhas de nylon?” – Antes de responder aos nossos amigos pescadores, vamos tecer alguns comentários sobre as super-linhas.<br/><br/>Há poucos anos, foi descoberta uma fibra sintética (SPECTRA), que é a matéria prima de quase todas as super-linhas, e que consiste em microfilamentos trançados para compor uma única linha fina. Comparativamente, a linha de nylon é quatro vezes inferior à resistência de uma super-linha, se levarmos em consideração a mesma milimetragem ou, inversamente, em linhas com resistência igual, uma super-linha tem a metade do diâmetro das linhas convencionais (monofilamentos).<br/><br/>Temos que ressaltar como propriedade positiva, a elasticidade, já que a convencional possui 25% e a super-linha não ultrapassa a 5% e em razão disso,a força aplicada por você no caniço é toda transmitida mais rapidamente até a extremidade ( chumbada com anzóis), conseqüentemente trazendo uma maior sensibilidade na ferrada do peixe. Deve-se estar atento para o balanceamento que deve existir no conjunto: vara, molinete e diâmetro da super-linha, em função das características específicas das diversas modalidades de pesca e do peixe.<br/><br/>Já existem, nas casas que vendem material de pesca, diversas marcas das super-linhas, embora o seu preço seja “salgado”. Devemos observar o aspecto da resistência e durabilidade, haja vista, segundo os fabricantes, a nova fibra sintética seja imune aos raios ultravioletas do sol que atacam as linhas de nylon, deixando-as mais frágeis e com um alto grau de ressecamento.<br/><br/>Conforme registros de indicações industriais, a garantia é de até 3 anos, em condições normais.É bom lembrar aqui os pontos contraditórios no uso das super-linhas, nas nossas pescarias e, inicialmente registramos que a baixa elasticidade não favorece a amortização dos trancos nos lançamentos; ao praticar a ferrada, procure amaciar o arranque, a fim de não romper a boca do peixe.</p>
<h3 align="center">CARACTERÍSTICAS DAS LINHAS</h3>
<div align="center"><img src="imagens/linhas.jpg" ></div>
<p><h3>Diâmetro</h3>O diâmetro, também chamado de bitola, espessura ou grossura, da linha é quase sempre informado em milímetros pelos fabricantes. Existem alguns raros que fornecem esta medida em polegadas. É preciso tomar cuidado para não confundir.<br/><br/>Naturalmente, em linhas de um mesmo tipo, o maior diâmetro proporcionará uma maior resistência, ou seja, aguentará um maior peso. Entretanto, não é na resistência ao peso que se deve pensar na hora de optar por uma linha de maior diâmetro e sim na sua resistência ao desgaste, que também tem relação direta à medida.<br/><br/>Quanto mais grossa for a linha, maior será sua resistência ao desgaste. É necessário prevenir quanto a isto no caso de pescas realizadas em locais onde a linha poderá sofrer atrito com galhos, pedras e outros obstáculos.<br/><br/>É preciso saber o que é mais importante para você: muita linha ou muita resistência? Quanto maior o diâmetro maior resistência, e menos linha você poderá carregar no carretel.</p>
<p><h3>Resistência</h3>É a capacidade máxima de suporte de peso de uma linha e normalmente vem expressa em libras ou em kg força nos carretéis. Cada libra correspondem a 453 gramas. Escolhe-se a resistência em função do peso do peixe desejado, mas é preciso lembrar que o seu peso se multiplica na água durante uma briga, sendo muito maior que o peso dele parado.<br/><br/>Além de ficar atento a libragem da linha, é preciso equilibrar o tipo de linha com a vara a ser utilizada na pescaria. Essa informação vem em algumas varas, no blank é possível identificar a libragem da linha correta para o equipamento.</p>
<p><h3>Memória</h3>As linhas tendem a assumir forma espiralada em razão de seu acomodamento no carretel. Isto é a capacidade de memória da linha. Dependendo da composição dos materiais utilizados na sua fabricação, esta propriedade varia.<br/><br/>Quanto menor memória melhor, pois a deformação pode causar desgaste na linha. Vale ressaltar que as linhas de multifilamento não possuem memória, sendo as linhas de nylon as que produzem esse efeito, e em alguns casos as de monofilamento.</p>
<p><h3>Linhas coloridas ou transparentes</h3>As linhas coloridas são preferidas pelos praticantes de pesca com isca artificial por proporcionarem grande visibilidade. Neste tipo de pesca é importante ver por onde passam as linhas ou onde caíram as iscas, pois a precisão dos arremessos é fundamental no sucesso da pescaria.<br/><br/>Já quando se trata de pesca com iscas artificiais, a maioria dos pescadores preferem utilizar linhas transparentes por acreditarem que os peixes podem perceber a linha e não atacar a isca.</p>
<p><h3>Tipos de filamento</h3>Existem dois tipos básicos de linhas quanto ao filamento: linhas mono e multifilamento. As linhas monofilamento são confeccionadas com apenas um filamento, como o próprio nome sugere. São as mais tradicionais e abundantes no mercado.<br/><br/>As de multifilamento, relativa novidade, podem ser linhas trançadas ou fundidas. Como um cabo, são constituídas por múltiplos filamentos cuja união proporciona uma linha de grande resistência de peso máximo e de desgaste. As linhas fundidas são assim chamadas por serem feitas de vários filamentos colados e não trançados cobertos por uma camada de gel, que faz com que tenham uma aparência lisa.<br/><br/>Uma linha multifilamento tem resistência muito maior que outra monofilamento de mesmo diâmetro e provoca uma abrasão maior, e por isso mesmo deve ser utilizada com varas cujos passadores resistam a este desgaste. Este tipo de linha oferece a possibilidade de você ter no carretel muita linha de grande resistência e de baixa memória.</p>
<p><h3>DICAS NA UTILIZAÇÃO DAS LINHAS</h3>Deve-se sempre optar pela linha mais fina possível dentro dos limites do peixe que se pretende pescar e da categoria do equipamento utilizado.</p>
<ul>
<li>Na captura de um peixe grande, em local sem enrosco, é mais importante ter bastante linha, do que ter linha grossa;</li>
<li>A linha mais fina proporciona maior sensibilidade e arremessos mais longos;</li>
<li>As linhas macias assentam melhor no bobina, desenrolam melhor e tem menos memória (forma espiralada que a linha assume com o passar do tempo, quando enrolada);</li>
<li>Em carretilha, as linhas macias, provocam menos cabeleira, além de serem mais resistentes a trancos, pois possuem maior elasticidade;</li>
<li>Dependendo do local onde se vai pescar a “cor ” da linha é um fator muito importante e isso somente se aprende com a experiência de anos de prática ou freqüentando escolas de pesca. Além disto, os companheiros podem sempre ajudar.</li>
</ul>
<hr>
<?php include "footer.inc";?>

</body>
</html>