<nav class="menu">
        <ul class="clearfix">
<li><a href="index.php">Home</a></li>
            <li>
                <a href="#">Equipamentos <span class="arrow">&#9660;</span></a>
 
                <ul class="sub-menu">
                    <li><a href="varas.php">Varas</a></li>
                    <li><a href="molinetes.php">Molinetes</a></li>
                    <li><a href="carretilhas.php">Carretilhas</a></li>
                    <li><a href="iscas.php">Iscas</a></li>
                    <li><a href="anzois.php">Anzóis</a></li>
                    <li><a href="boias.php">Bóias</a></li>
                    <li><a href="chumbos.php">Chumbos</a></li>
                    <li><a href="linhas.php">Linhas</a></li>
                </ul>
            </li>
            <li><a href="peixes.php">Peixes</a></li>
            <li><a href="dicas.php">Dicas</a></li>
	    <li><a href="login.php">Login</a></li>
	    <li><a href="forum.php">Fórum</a></li>
</ul>
</nav>