<!DOCTYPE html>
<html lang="pt-br">
<head>
<?php include "data.inc";?>
<meta charset="utf-8"/>
<link rel="stylesheet" type="text/css" href="estilo.css">
<title>Rei da Pesca</title>
</head>
<body>
<?php include "header.inc";?>
<?php include "menu.inc";?>
<br/><br/>
<hr>
<h1>Peixes</h1>
<h4>Aqui está listado os principais peixes de água doce e suas características:</h4>
<p><img src="imagens/abotoado.jpg" align=left hspace="10"><b>Abatoado:</b> O peixe Abotoado é um peixe de couro. Seu corpo é coberto por uma fileira de placas ósseas. O comprimento do seu corpo vai de 3 a 4cm até 1 metro aproximadamente. Possui coloração cinza escura uniforme, cabeça estreita, focinho longo, boca inferior, olhos grandes e presença de barbilhões curtos. Sua boca inferior e sem dentes, bem como focinho longo servem para conseguir os alimentos. Ele pode chegar aos 80 cm de comprimento e atingir até 10Kg.</p><hr>
<p><img src="imagens/cachara.jpg" align=left hspace="10"><b>Cachara:</b> O Chacara é um peixe de couro. Possui o corpo alongado e roliço. Tem cabeça grande e achatada. Sua coloração é cinza escura, no dorso, clareando em direção ao ventre, sendo branca abaixo da linha lateral. Pode ser separada das outras espécies do gênero pelo padrão de manchas: faixas verticais pretas irregulares, começando na região dorsal e se estendendo até abaixo da linha lateral. Às vezes, apresenta algumas manchas arredondadas ou alongadas no final das faixas. Espécie de grande porte, pode alcançar 1,2m de comprimento e atingir 20kg.</p><hr>
<p><img src="imagens/cachorra.jpg" align=left hspace="10"><b>Cachorra:</b> O Cachorra possui escamas diminutas, corpo alto e comprimido. Sua boca é oblíqua, com uma fileira de dentes  e um par de presas na mandíbula. Estas são tão grandes que a maxila superior possui dois buracos para acomodá-los quando a boca está fechada. Suas nadadeiras peitorais são grandes. Possui coloração prata uniforme com uma mancha preta alongada atrás do opérculo. Pode alcançar mais de 1 m de comprimento total.</p><hr>
<p><img src="imagens/cascudo.jpg" align=left hspace="10"><b>Cascudo:</b> O peixe Cascudo é um peixe que possui uma couraça recobrindo o seu corpo. Na verdade, são pequenas placas ósseas adaptadas à maneira de escamas, que percorrem o corpo em várias fileiras (de três a quatro), o que confere ao Cascudo aparência visual e sensação tátil de lixa. Seu corpo possui coloração parda com algumas manchas escuras. Sua região ventral é geralmente nua. Tem boca inferior (ventral). Pode atingir os 39 cm e alcançar 1,5 kg de peso.</p><hr>
<p><img src="imagens/dourado.jpg" align=left hspace="10"><b>Dourado:</b> O Dourado é um peixe muito apreciado por seu sabor, sendo conhecido como o “Rei do Rio”. É um peixe de escamas. Cada escama tem um pequeno risco preto no meio, formando linhas longitudinais da cabeça à cauda. Possui uma coloração dourada por todo o corpo, com reflexos avermelhados. Tem uma cabeça grande, com uma boca que alcança a metade desta, repleta de caninos em forma cônica. Possui uma barbatana caudal bastante robusta. Pode atingir mais de 25 kg e alcançar 1m de comprimento.</p><hr>
<p><img src="imagens/jau.jpg" align=left hspace="10"><b>Jaú:</b>O Jaú é considerado um dos maiores peixes de couro da região Amazônica e, certamente, da região Neotropical. Sua cabeça é bastante ampla e achatada, enquanto que o corpo se afina bastante rapidamente em direção à cauda. Possui boca bem desenvolvida e nadadeiras peitorais e dorsal com espinhos. Sua coloração é parda ou verde-azeitona e o ventre, esbranquiçado. Pode atingir 1,90 m de comprimento e mais de 100 kg de peso.</p><hr>
<p><img src="imagens/lambari.jpg" align=left hspace="10"><b>Lambari:</b> O Lambari é um pequeno peixe de escamas, com coloração prateada, e nadadeiras variando entre  amarela, vermelha e o preta. Seu corpo é alongado e um pouco comprimido. Possui duas manchas, sendo uma próxima à nadadeira peitoral, com forma ovalada e posição horizontal, e outra em forma de clava, seguindo do pedúnculo caudal à porção mediana do corpo. Chega, ao máximo, a 200mm de comprimento.</p><hr>
<p><img src="imagens/matrinxa.jpg" align=left hspace="10"><b>Matrinxã:</b> O Matrinxã é um peixe de escamas. Sua carne é muito apreciada nas regiões Centro Oeste e Norte do país. Possui corpo alongado, um pouco alto e comprimido. Sua coloração é prateada, com as nadadeiras alaranjadas, sendo a nadadeira caudal escura. Apresenta uma mancha arredondada escura na região umeral. Os dentes são fortes, multicuspidados, dispostos em várias fileiras na maxila superior. Pode chegar aos 80 cm de comprimento e 5 Kg de peso.</p><hr>
<p><img src="imagens/pacu.jpg" align=left hspace="10"><b>Pacu:</b> O Pacu é um peixe de escamas pequenas e numerosas. Sua coloração é cinza-escura, no dorso, e amarelo-dourada, no ventre, podendo variar devido o ambiente. Tem corpo comprimido, alto e em forma de disco, apresentando quilha ventral com espinhos, cujo número pode variar de 6 a 70. Seus dentes são molariformes. Possui carne muito saborosa, por isso é muito pescado. É uma espécie que vem sendo muito utilizada na piscicultura e para a formação do híbrido Tambacu em cruzamento com o Tambaqui. Pode alcançar mais de 70 cm de comprimento e pesar até 20 Kg.</p><hr>
<p><img src="imagens/pintado.jpg" align=left hspace="10"><b>Pintado:</b> O Pintado é um peixe de couro, com coloração acinzentada e diversas pintas pretas cilíndricas pelo corpo. Já seu ventre tem uma coloração esbranquiçada. Seu corpo é alongado e roliço. Sua cabeça é grande e achatada, com dimensão entre 1/4 a 1/3 do tamanho do corpo. Apresenta longos barbilhões. Possui ferrões junto às nadadeiras laterais e dorsal. É apreciado por sua carne muito saborosa. Pode alcançar pesos próximos a 80 kg e quase 2 m de comprimento.</p><hr>
<p><img src="imagens/piraiba.jpg" align=left hspace="10"><b>Piraíba:</b> O Piraíba é o maior peixe de couro da Bacia Amazônica, podendo alcançar 3 m de comprimento e 150 Kg de peso. Possui corpo roliço, cabeça deprimida, com os olhos pequenos e situados no seu topo. Seus barbilhões maxilares são roliços e muito longos, cerca de duas vezes o tamanho do corpo, nos jovens, e cerca de 2/3 do corpo, no adulto. O segundo par de barbilhões mentonianos é pequeno, alcançando apenas a base da nadadeira peitoral. Sua boca é subinferior, com a placa dentígera da maxila superior localizada parcialmente à frente daquela da maxila inferior. Os jovens apresentam o corpo de coloração clara, com varias máculas escuras e arredondadas na sua porção terminal superior, as quais desaparecem à medida que o peixe cresce. Nos adultos, a coloração é cinza-escura-amarronzada, no dorso, e clara, no ventre. Sua carne não é apreciada, pois muitos acreditam que faz mal e transmite doenças.</p><hr>
<p><img src="imagens/pirara.jpg" align=left hspace="10"><b>Pirara:</b> O Pirarara é um peixe de couro, de corpo robusto. Sua cabeça é ossificada, achatada e grande, apresentando um forte contra-sombreado, assim como as nadadeiras adiposa, dorsal e anal de cor alaranjada brilhante. Apresenta coloração do corpo cinza-escura, com uma faixa longitudinal branco-amarelada, ao longo dos flancos,  indo da  cabeça à nadadeira caudal. Pode chegar aos 50 kg e alcançar 1,3 m do focinho à separação dos dois lobos da nadadeira caudal.</p><hr>
<p><img src="imagens/pirarucu.jpg" align=left hspace="10"><b>Pirarucu:</b> O peixe Pirarucu é o maior peixe de escamas de água doce do Brasil e um dos maiores do mundo. Possui corpo em forma cilíndrica, cabeça achatada e mandíbulas salientes. Seus olhos são amarelados e de pupila azulada, um tanto salientes. Sua coloração é marrom-esverdeada, escura no dorso a avermelhada nos flancos, sendo a intensidade variável de acordo com o tamanho do individuo e com o tipo de água em que vive.  É  uma  espécie  que  tem  respiração  acessória, utilizando-se do oxigênio dissolvido na água, mas principalmente do ar e, por isso, tem que subir frequentemente à superfície d'água. Pode viver mais de 18 anos. Devido à sua excelente carne, é considerado “o Bacalhau Brasileiro”. Pode atingir comprimento máximo de 2,10 m e 112 Kg de peso.</p><hr>
<p><img src="imagens/tambaqui.jpg" align=left hspace="10"><b>Tambaqui:</b> O Tambaqui é um peixe de escamas, com corpo romboidal, alto, achatado e serrilhado no peito.  Apresenta uma dentição poderosa, adaptada para quebrar as duras castanhas que fazem parte de sua dieta. Em suas brânquias, podem ser observados espinhos longos e finos. Possui nadadeira adiposa curta, com raios na extremidade, dentes molariformes e rastros branquiais longos e numerosos. Sua coloração é parda, na metade superior, e preta, na metade inferior do corpo, mas pode variar para mais clara ou mais escura dependendo da cor da água. Tem a carne bastante apreciada. Pode alcançar  90 cm  de comprimento e atingir 30 Kg.</p><hr>
<p><img src="imagens/tilapia.jpg" align=left hspace="10"><b>Tilapia:</b> A Tilápia é um peixe de escamas, com corpo um pouco alto e comprimido. Possui coloração verde-oliva prateada, com sobras verticais negras. A cor da nadadeira dorsal também é verde-oliva, com uma linha vermelha e branca até cinza-escuro com pontos oblíquos. Já a nadadeira caudal é pontuada na porção dorsal, vermelha ou amarela na porção ventral. Pode atingir 45 cm de comprimento e 2,5 kg de peso.</p><hr>
<p><img src="imagens/traira.jpg" align=left hspace="10"><b>Traíra:</b> A Traíra é um peixe de escamas. Possui corpo cilíndrico, boca grande, olhos grandes e nadadeiras arredondadas, exceto a dorsal. Sua coloração é marrom ou preta manchada de cinza. Possui dentes poderosos e afiadíssimos. Sua língua é áspera ao tato, o que a diferencia do trairão, que apresenta a língua lisa. É um peixe utilizado em açudes e represas como controlador de populações demasiadamente prolíficas, como tilápias e piabas. Tem alta resistência a locais com pouco oxigênio. Apesar do excesso de espinhas, em algumas regiões é bastante apreciado como alimento.  Pode atingir 60 cm de comprimento e 4 K de peso.</p><hr>
<p><img src="imagens/tucunare.jpg" align=left hspace="10"><b>Tucunaré:</b> O Tucunaré é um peixe de escamas, com corpo alongado e um pouco comprimido. Sua coloração e amarelada, com manchas pretas e verticais distribuídas regularmente pelo corpo. Todos os Tucunarés apresentam uma mancha redonda (ocelo) no pedúnculo caudal. É bastante rápido, agressivo, forte e até estúpido. Também é muito sedentário (não realizando migrações). Tem hábitos diurnos. Pode chegar a  30 cm ou mais de 1 m de comprimento total.</p>
<hr>   
<?php include "footer.inc";?>

</body>
</html>